import { combineReducers } from '@reduxjs/toolkit';
import { History } from 'history';
import { connectRouter } from 'connected-react-router';

import {
  appModule,
  authModule,
  editorModule,
  editorAreaModule,
  editorDragModule,
  editorHistoryModule,
  editorIslandModule,
  editorKeyModule,
  editorLayerModule,
  editorLayoutModule,
  editorLineModule,
  editorNodeModule,
  editorOpModule,
  editorPreferenceModule,
  editorShapeModule,
  editorTableModule,
  editorViewModule,
  editorWallModule,
  inventoryDataModule,
  mapModule,
  mapVersionModule,
  storeModule,
  viewerModule,
  viewerLayoutModule,
  viewerNodeModule,
  viewerPreferenceModule,
  viewerProductLocationModule,
  viewerShapeModule,
  viewerViewModule,
} from '../modules';

import { companyModule } from '../modules/company';
export const createRootReducer = (history: History) =>
  combineReducers({
    app: appModule.reducer,
    auth: authModule.reducer,
    editor: editorModule.reducer,
    editorArea: editorAreaModule.reducer,
    editorDrag: editorDragModule.reducer,
    editorHistory: editorHistoryModule.reducer,
    editorIsland: editorIslandModule.reducer,
    editorKey: editorKeyModule.reducer,
    editorLayer: editorLayerModule.reducer,
    editorLayout: editorLayoutModule.reducer,
    editorLine: editorLineModule.reducer,
    editorNode: editorNodeModule.reducer,
    editorOp: editorOpModule.reducer,
    editorPreference: editorPreferenceModule.reducer,
    editorShape: editorShapeModule.reducer,
    editorTable: editorTableModule.reducer,
    editorView: editorViewModule.reducer,
    editorWall: editorWallModule.reducer,
    inventoryData: inventoryDataModule.reducer,
    map: mapModule.reducer,
    mapVersion: mapVersionModule.reducer,
    store: storeModule.reducer,
    viewer: viewerModule.reducer,
    viewerLayout: viewerLayoutModule.reducer,
    viewerNode: viewerNodeModule.reducer,
    viewerPreference: viewerPreferenceModule.reducer,
    viewerProductLocation: viewerProductLocationModule.reducer,
    viewerShape: viewerShapeModule.reducer,
    viewerView: viewerViewModule.reducer,
    router: connectRouter(history),
    company: companyModule.reducer,
    });
